# Generated by Django 5.1.5 on 2025-05-22 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_abstractlogmodel_ipaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractlogmodel',
            name='StatusCode',
        ),
    ]
