# Generated by Django 5.1.5 on 2025-02-03 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('association', '0001_initial'),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='Department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='department.department'),
        ),
    ]
