# Generated by Django 5.1.5 on 2025-06-14 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0002_initial'),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='Department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department'),
        ),
    ]
