# Generated by Django 5.1.5 on 2025-06-30 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='Administrator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administrator.administrator'),
        ),
    ]
