# Generated by Django 5.1.5 on 2025-03-12 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('association', '0002_initial'),
        ('core', '0001_initial'),
        ('department', '0001_initial'),
        ('publicService', '0003_methods_publicservice_restricted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationPermission',
            fields=[
                ('abstractpermission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.abstractpermission')),
                ('Association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='association.association')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.abstractpermission',),
        ),
        migrations.CreateModel(
            name='DepartmentPermission',
            fields=[
                ('abstractpermission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.abstractpermission')),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.abstractpermission',),
        ),
        migrations.CreateModel(
            name='PublicServicePermission',
            fields=[
                ('abstractpermission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.abstractpermission')),
                ('PublicService', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicService.publicservice')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.abstractpermission',),
        ),
    ]
