global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
- job_name: central_access_management
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /promMetrics
  scheme: http
  follow_redirects: true
  static_configs:
  - targets:
    - localhost:8020