# Generated by Django 5.1.5 on 2025-02-12 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0002_initial'),
        ('grantee', '0002_grantee_association'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantee',
            name='Association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='association.association'),
        ),
    ]
