# Generated by Django 5.1.5 on 2025-06-14 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0003_alter_association_department'),
        ('grantee', '0003_alter_grantee_association'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantee',
            name='Association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='association.association'),
        ),
    ]
