# Generated by Django 5.1.5 on 2025-06-30 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
        ('grantee', '0004_alter_grantee_association'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantee',
            name='Administrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.administrator'),
        ),
        migrations.AlterField(
            model_name='grantee',
            name='Citizen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
