# Generated by Django 5.1.5 on 2025-02-12 09:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('association', '0002_initial'),
        ('grantee', '0003_alter_grantee_association'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PublicId', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Title', models.CharField(max_length=100, unique=True)),
                ('MachineName', models.CharField(max_length=150, unique=True)),
                ('Description', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
                ('URL', models.URLField(unique=True)),
                ('Association', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='association.association')),
                ('Grantee', models.ManyToManyField(to='grantee.grantee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
