# Generated by Django 5.1.5 on 2025-06-16 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0003_alter_association_department'),
        ('publicService', '0003_methods_publicservice_restricted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicservice',
            name='Association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='association.association'),
        ),
    ]
