# Generated by Django 5.1.5 on 2025-03-12 14:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemCron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PublicId', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('CronName', models.CharField(choices=[('SaveSystemLog', 'SaveSystemLog')], default='SaveSystemLog')),
                ('Message', models.CharField(null=True)),
                ('FinishedAt', models.DateTimeField()),
                ('Success', models.BooleanField(default=False)),
                ('Failure', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
