# Generated by Django 5.1.5 on 2025-02-17 09:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grantee', '0003_alter_grantee_association'),
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PublicId', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Message', models.CharField(max_length=300)),
                ('Decline', models.BooleanField(default=False)),
                ('StartDate', models.DateTimeField(null=True)),
                ('EndDate', models.DateTimeField(null=True)),
                ('Grantee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='grantee.grantee')),
                ('Request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='request.request')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
