# Generated by Django 5.1.5 on 2025-06-14 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant', '0001_initial'),
        ('grantee', '0004_alter_grantee_association'),
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='Grantee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grantee.grantee'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='Request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='request.request'),
        ),
    ]
