# Generated by Django 5.1.5 on 2025-05-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceSession', '0002_servicesession_ipaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesession',
            name='LastSeen',
            field=models.DateTimeField(null=True),
        ),
    ]
