# Generated by Django 5.1.5 on 2025-06-14 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicService', '0003_methods_publicservice_restricted_and_more'),
        ('serviceSession', '0003_servicesession_lastseen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesession',
            name='Citizen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicesession',
            name='Service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicService.publicservice'),
        ),
    ]
