# Generated by Django 5.1.5 on 2025-02-17 09:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publicService', '0002_publicservice_visibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PublicId', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Subject', models.CharField(max_length=50)),
                ('Message', models.CharField(max_length=500)),
                ('Citizen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('PublicService', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publicService.publicservice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
