# Generated by Django 5.1.5 on 2025-03-12 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministratorLog',
            fields=[
                ('abstractlogmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.abstractlogmodel')),
                ('Administrator', models.CharField()),
            ],
            options={
                'abstract': False,
            },
            bases=('core.abstractlogmodel',),
        ),
        migrations.CreateModel(
            name='CitizenLog',
            fields=[
                ('abstractlogmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.abstractlogmodel')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.abstractlogmodel',),
        ),
        migrations.CreateModel(
            name='GranteeLog',
            fields=[
                ('abstractlogmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.abstractlogmodel')),
                ('Grantee', models.CharField()),
            ],
            options={
                'abstract': False,
            },
            bases=('core.abstractlogmodel',),
        ),
        migrations.CreateModel(
            name='SiteManagerLog',
            fields=[
                ('abstractlogmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.abstractlogmodel')),
                ('SiteManager', models.CharField()),
            ],
            options={
                'abstract': False,
            },
            bases=('core.abstractlogmodel',),
        ),
    ]
